### ISSUE TITLE
[Clarification] Magic Rules

### ISSUE THREAD

**Issue by Web-eWorks** [microluxe20/microluxe20#23]
As it stands, the rules for spellcasters and their abilities are uncomfortably vague. Do spellcasters make a Magic attack to cast a spell(with the target then making a check vs Spell DC), or is it automatic? The current rules text is completely unclear on this matter. Do spellcasters have an actual damage-dealing Magic attack, independent of their spells?

Additionally, the rules are completely lacking a section on wands, staves, potions, etc, as well as the dubious 'spell components'. This might not be so bad with a background coming from D&D/d20, but A: I've never played D&D in my life, and B: this is supposed(if I'm remembering it right) to be a batteries-included rule system.

I've got a PR in the works with some fixes to errors in the rules, but I wanted to get some information on this.

**Comment by kgrubb** [comment]
__Casting Spells__

The spellcaster section is one of the parts that has been the most-changed, and I agree. A lot of it still lacks clarity. At the moment, all spells require some kind of save if cast against an animate object. Instead of rolling an attack roll, the target of the spell (if its not inanimate) must make a DC save against the spellcaster's DC. 

__Spellcaster Base Attacks__

Spellcasters do not have any special magical attack outside of their spell list. They can attack with melee weapons if needed, and their cantrips are minimal in cost. Have you found this to be inadequate for spellcasters in actual gameplay? If so, perhaps spellcasters could have a zero-cost basic magical attack.

__Spell Components__

I shied away from a traditional, vanican "component-based" spellcasting, instead opting for a point-based spell system. I have kept magical items out of the rules, expecting GM's to fill that void however they want to, but if this is something that is fairly uniform to implement, I'm cool with a "magical items" section that goes over wands, staves, potions, and other alchemical ingredients.

**Comment by Web-eWorks** [comment]
Normal weapons for spellcasters are fine. It was more an issue of the terminology used - 'magic attack' vs 'magic action' or the like - and confusion on when such a roll would even be necessary.

On the spell components, there's a throwaway line in the equipment section on needing spell components to cast spells (as a Mage, I think), but _literally_ nothing else to back this up or explain it.

For magical items, I think it would be pretty simple to implement - the rules for creating magical items state that they can be created for 'half their gp cost', but there's never a baseline established for their cost or abilities. A simple table and a few paragraphs for the GM on creating such items would suffice, I think.

I'll see about whipping up an initial PR with these changes.

**Comment by Web-eWorks** [comment]
How close to the SRD do you want to run wands, staves, etc? I was thinking loose guidelines for the setting along the lines of:
+ Wands: prepackaged spells+charges. Probably be usable by non-magical characters.
+ Rods / other Foci: can be etched to cast one non-class spell and/or free or reduced-cost metamagic (Extending/Empowering/Widening) when used for certain spells.
+ Staves: buffs to Magic Attack, improved/lower-level casting of class spells, perhaps integral utility spells (maybe with limited but rechargable uses).

Rods, staves, and wands are used by a successful Magic Attack; potions are drunk as a simple action.

**Comment by kgrubb** [comment]
I think what you've set up is good. A few things:

* With rods, what do you mean by non-class spells? In the case of d20srd, there's a good bit of non-class spells. However, in m20, there's not really a concept of non-class spells (although you can use the srd spells if you want to).

* for Staves, the "improved/lower-level casting" could be extremely powerful, so i'd like to test out some combinations with that.

**Comment by Web-eWorks** [comment]
By non-class spells, I mean being able to cast, say, Lightning Bolt (6th Level Mage) as a Illusionist of the appropriate level.

My influence on this is mostly Dresden Files and games like Brogue and Angband, so the eventual evolution of this is to be able to create 'blasting rods' that can function as a magical flamethrower and other such items.

An idea I had was that when casting spells with a staff or wand, the spell's DC was the result of a Magic Attack roll by the caster, instead of the flat 10 + caster level + MIND bonus. It would need some balancing, however, and I'm not especially convinced it's worth the added complexity.

**Comment by kgrubb** [comment]
Ah, I see what you mean. That makes perfect sense in my mind. As long as the rod info includes some clarity on what non-class spells would entail, I think that'd be a great addition. 

As for the magic attack rolls with staves/wands, I'll try and run a test game with something like this and see how it plays out.

**Comment by Web-eWorks** [comment]
So I have a level 7 druid in my game who has a Magic bonus of +11. At this point, the Spell DC for the character is 21, which makes the character's spells unavoidable. I would propose moving magic attacks to an active-roll system, allowing there to be a chance (however small) for a character's spells to fail even at high levels, and allowing spellcasters a more active role in casting spells.

I don't have a system outlined yet, but I'll see what I can come up with.

**Comment by kgrubb** [comment]
For monsters, I have typically given them base stats to work with and use a "Will" save (Mind bonus + d20) against the Spell DC. For a level 7 monster, if we give the monster completely flat, even stats, the monster's stats should be something like (**STR** 4, **DEX** 4, **MIND** 4). This would yield a d20+2 (+ situational modifiers) for a **MIND**-based save, making the monster have a 10% chance of avoiding the spell (plus the situational mods). If the monster was given a more **MIND** based setup (**STR** 4, **DEX** 0, **MIND** 8), the probability could increase up to about a 40% chance to avoid the spell. Does that seem ok, or do you feel like that is too low?

**Comment by Web-eWorks** [comment]
Much better. I still want to explore moving spellcasting to a more active system (i.e. the caster makes a roll to determine success), as it meshes with the rest of the game better, but this is a more-than-acceptable interim measure.

An idea I wanted to throw out for your consideration was having spell damage scale with the number of attacks. Normal characters get a damage boost with the additional attacks from attack bonus, but the magic attack bonus isn't even used for spellcasting. Something like Produce Flame from the Druid's list might deal +1d6 damage for every successful 'bonus attack' beyond the first. Would make an interesting way to keep spells relevant as the character advances.

**Comment by kgrubb** [comment]
Alright, so to make this a little bit easier to follow, Let's break this out into a few different issues and tackle them one at a time. Currently, I've got the following list:

1. Attack-based (instead of save based) Spellcasting(#29)
2. Magic Attack Bonus Usage Clarity(#30)
3. Spell Component/Requirements Clarity(#31)
4. Magic Item Creation Table/Section(#32)

I'll try to make pr's to the 1.7.4 proposed changes first, and then we can tackle the other 2 issues for a 1.8.0 release.

**Comment by kgrubb** [comment]
Merged!
